### ISSUE TITLE
和cisco代理冲突的问题

### ISSUE THREAD

**Issue by binary-jerry** [wenjunxiao/mac-docker-connector#10]
mac和docker服务通信，docker服务由于安全问题需要启动cisco代理才可以启动，在cisco代理软件连接后，mac-docker-connector失效，无法进行mac和docker之间的通信，但关闭cisco后，使用一个测试的docker服务是可以的。我对于网络方面的知识了解比较少，可以帮忙解决这个问题吗

**Comment by wenjunxiao** [comment]
> mac和docker服务通信，docker服务由于安全问题需要启动cisco代理才可以启动，在cisco代理软件连接后，mac-docker-connector失效，无法进行mac和docker之间的通信，但关闭cisco后，使用一个测试的docker服务是可以的。我对于网络方面的知识了解比较少，可以帮忙解决这个问题吗

启用cisco之后应该是由于cisco修改了路由表导致原来路由到mac-docker-connector的路由表失效导致。可以尝试启动cisco之后再重启mac-docker-connector，如果不行可以把路由表打印出来看下

**Comment by binary-jerry** [comment]
我尝试了先启动cisco之后再重启mac-docker-connector，还是不行。在启动cisco后，看了路由表的信息，172.17这个docker网段的路由表信息确实被修改了，我需要将网段修改回来吗？

**Comment by wenjunxiao** [comment]
> 我尝试了先启动cisco之后再重启mac-docker-connector，还是不行。在启动cisco后，看了路由表的信息，172.17这个docker网段的路由表信息确实被修改了，我需要将网段修改回来吗？

如果cisco和docker使用相同的网段，那必须有一个需要调整，具体要看路由表和网段信息来决定
