### ISSUE TITLE
mac bigsur  mac-docker-connector不断重启 和 ping不通

### ISSUE THREAD

**Issue by aqiuxx** [wenjunxiao/mac-docker-connector#14]
您好，我按照教程都设置了，但是mac-docker-connector 不断重启和无法ping通其他的容器

系统： macos high bigsur
docker桌面版本：docker desktop 4.16.2， docker :20.10.22

命令：
```
sudo brew services start docker-connector
docker run -it -d --restart always --net host --cap-add NET_ADMIN --name connector wenjunxiao/mac-docker-connector
```

```
# cat /usr/local/etc/docker-connector.conf                                                                                                                                                     
route 172.17.0.0/16
route 172.18.0.0/16
route 172.100.0.0/16
```

错误
```
# cat /usr/local/var/log/docker-connector.log                                                                                                                                                   
2023/02/13 18:48:01 load config(true) => /usr/local/etc/docker-connector.conf
2023/02/13 18:48:01 error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted
2023/02/13 18:48:11 load config(true) => /usr/local/etc/docker-connector.conf
2023/02/13 18:48:11 error in syscall.RawSyscall(syscall.SYS_CONNECT, ...): operation not permitted
```

**Comment by wenjunxiao** [comment]
@qiuzhichang  确认以sudo运行的服务。如果确认以sudo运行，那么尝试关闭Mac的SIP再运行看是否可以

**Comment by aqiuxx** [comment]
我将docker桌面版本升级到了4.17.0：docker desktop 4.17.0， docker :20.10.23
没有上面operation not permitted的报错了，但是还是在不断重启，日志如下


```
# cat /usr/local/var/log/docker-connector.log  

2023-03-02 11:11:46 interface => tun0
2023-03-02 11:11:46 command => ip addr add dev tun0 local 192.168.251.1 peer 192.168.251.2
2023-03-02 11:11:46 command => ip route add 192.168.251.0/24 via 192.168.251.2 dev tun0
2023-03-02 11:11:56 invalid address => host.docker.internal:2511

```

**Comment by aqiuxx** [comment]
<img width="865" alt="image" src="https://user-images.githubusercontent.com/19370351/222323721-06af7c1e-36ca-4365-bd84-1064c837c890.png">



我将docker desktop 的setting->Resources -> docker subnet改为 192.168.65.0/24,现在的结果如下，我不知道是否正常了？

```
# cat /usr/local/var/log/docker-connector.log  

2023-03-02 11:26:50 interface => tun0
2023-03-02 11:26:50 command => ip addr add dev tun0 local 192.168.251.1 peer 192.168.251.2
2023-03-02 11:26:50 command => ip route add 192.168.251.0/24 via 192.168.251.2 dev tun0
2023-03-02 11:26:50 local => 192.168.65.4:49289
2023-03-02 11:26:50 remote => 192.168.65.2:2511
```

host 也能ping通容器了
```
# ping 172.17.0.2 
PING 172.17.0.2 (172.17.0.2): 56 data bytes
64 bytes from 172.17.0.2: icmp_seq=0 ttl=63 time=20.230 ms
64 bytes from 172.17.0.2: icmp_seq=1 ttl=63 time=7.304 ms
64 bytes from 172.17.0.2: icmp_seq=2 ttl=63 time=4.923 ms
64 bytes from 172.17.0.2: icmp_seq=3 ttl=63 time=2.549 ms
```

**Comment by wenjunxiao** [comment]
@aqiuxx 看起来前一次报错是 host.docker.internal 这个域名没有解析到正确的地址导致，现在可以ping通就可以正常使用了

**Comment by yubobo** [comment]
> <img alt="image" width="865" src="https://user-images.githubusercontent.com/19370351/222323721-06af7c1e-36ca-4365-bd84-1064c837c890.png">
> 
> 我将docker desktop 的setting->Resources -> docker subnet改为 192.168.65.0/24,现在的结果如下，我不知道是否正常了？
> 
> ```
> # cat /usr/local/var/log/docker-connector.log  
> 
> 2023-03-02 11:26:50 interface => tun0
> 2023-03-02 11:26:50 command => ip addr add dev tun0 local 192.168.251.1 peer 192.168.251.2
> 2023-03-02 11:26:50 command => ip route add 192.168.251.0/24 via 192.168.251.2 dev tun0
> 2023-03-02 11:26:50 local => 192.168.65.4:49289
> 2023-03-02 11:26:50 remote => 192.168.65.2:2511
> ```
> 
> host 也能ping通容器了
> 
> ```
> # ping 172.17.0.2 
> PING 172.17.0.2 (172.17.0.2): 56 data bytes
> 64 bytes from 172.17.0.2: icmp_seq=0 ttl=63 time=20.230 ms
> 64 bytes from 172.17.0.2: icmp_seq=1 ttl=63 time=7.304 ms
> 64 bytes from 172.17.0.2: icmp_seq=2 ttl=63 time=4.923 ms
> 64 bytes from 172.17.0.2: icmp_seq=3 ttl=63 time=2.549 ms
> ```

我遇到了同样的问题。一样的版本，一样的报错。
但是你改的这个地方，它本来就是设置的192.168.65.0/24   你到底是改动了哪里？解决的问题。谢谢～
