### ISSUE TITLE
macos Ventura mac-docker-connector不断重启 和 ping不通容器

### ISSUE THREAD

**Issue by yubobo** [wenjunxiao/mac-docker-connector#15]
mac docker desktop 4.17.0
<img width="798" alt="image" src="https://user-images.githubusercontent.com/4443390/226089727-6921920d-5e18-4759-b8fb-f7ff5ede2b68.png">

根据教程配置完毕，使用命令 ：
docker run -it -d --restart always --net host --cap-add NET_ADMIN --name connector wenjunxiao/mac-docker-connector
启动。
但是频繁重启：
<img width="757" alt="image" src="https://user-images.githubusercontent.com/4443390/226089771-40f119a5-c99e-41f1-8483-9deea04212be.png">

导致不可用。

**Comment by yubobo** [comment]
@wenjunxiao 谢谢～～

**Comment by wenjunxiao** [comment]
@yubobo 你的问题是`host.docker.internal`这个内置的域名无法解析导致，你可以进入任意容器中ping检查这个域名是否可用，可以参考docker的issue [2965](https://github.com/docker/for-mac/issues/2965) 看是否可以解决无法解析的问题。或者如果知道容器中访问host的IP地址(我windows在容器中解析出来是192.168.65.2），那么可以通过`--add-host=host.docker.internal:192.168.65.2`。或者找到替代的域名(比如[官网文档](https://docs.docker.com/desktop/networking/)中提到的`gateway.docker.internal`)然后在启动时增加启动参数 `docker run -it -d --restart always --net host --cap-add NET_ADMIN --name connector wenjunxiao/mac-docker-connector desktop-connector --host gateway.docker.internal`
