### ISSUE TITLE
mac 12.5 休眠后，connector 需重启后，宿主机才能才能 ping 通容器

### ISSUE THREAD

**Issue by chaseyan** [wenjunxiao/mac-docker-connector#16]
macos 版本 : 12.5
docker 版本: 
<img width="733" alt="image" src="https://user-images.githubusercontent.com/16630112/232350792-f169fb97-957c-4663-b21d-26443eb5a8cb.png">

connector版本及启动命令：
<img width="1559" alt="image" src="https://user-images.githubusercontent.com/16630112/232350951-b7fa2368-5213-41b0-b892-c7f012f4f803.png">

docker run -it -d --restart always --net host --cap-add NET_ADMIN --add-host=host.docker.internal:host-gateway --name connector wenjunxiao/mac-docker-connector

现象为每次 mac 休眠后，无法ping 通 ping 172.17.0.1，需要 restart docker 后恢复正常

非常感谢~期待答复~

**Comment by wenjunxiao** [comment]
> macos 版本 : 12.5 docker 版本: <img alt="image" width="733" src="https://user-images.githubusercontent.com/16630112/232350792-f169fb97-957c-4663-b21d-26443eb5a8cb.png">
> 
> connector版本及启动命令： <img alt="image" width="1559" src="https://user-images.githubusercontent.com/16630112/232350951-b7fa2368-5213-41b0-b892-c7f012f4f803.png">
> 
> docker run -it -d --restart always --net host --cap-add NET_ADMIN --add-host=host.docker.internal:host-gateway --name connector wenjunxiao/mac-docker-connector
> 
> 现象为每次 mac 休眠后，无法ping 通 ping 172.17.0.1，需要 restart docker 后恢复正常
> 
> 非常感谢~期待答复~

休眠后应该会自动恢复连接，具体需要看日志、路由等信息
