### ISSUE TITLE
MacBook M1 & Docker DeskTop 4.15.0 无法ping通172.17.0.2

### ISSUE THREAD

**Issue by zby-universal** [wenjunxiao/mac-docker-connector#19]
**看了下其他的issue，都说要desktop 4.15 于是降级重新安装了docker，按照流程配置最后还是无法ping 通。**

**docker-connector的启动日志正常：**
`2023-07-06 18:27:39 interface => tun0
2023-07-06 18:27:39 command => ip addr add dev tun0 local 192.168.251.1 peer 192.168.251.2
2023-07-06 18:27:39 command => ip route add 192.168.251.0/24 via 192.168.251.2 dev tun0
2023-07-06 18:27:39 local => 192.168.65.3:55811
2023-07-06 18:27:39 remote => 192.168.65.2:2511`

**docker inspect web 服务的容器，查看分配的ip地址就是172.17.0.2:**
<img width="781" alt="image" src="https://github.com/wenjunxiao/mac-docker-connector/assets/60498735/812f8d6e-cc77-4a59-ad5a-cdb96f999bd5">

docker-connector.conf也配置了路由:
route 172.17.0.0/16

**ping 172.17.0.2 超时：**
PING 172.17.0.2 (172.17.0.2): 56 data bytes
Request timeout for icmp_seq 0
Request timeout for icmp_seq 1
Request timeout for icmp_seq 2
Request timeout for icmp_seq 3
Request timeout for icmp_seq 4
Request timeout for icmp_seq 5

还有什么原因导致无法ping通呢？

**Comment by zhaoshaoquan** [comment]
我现在也是遇到同样的问题了，你解决了没的？感觉这个作者没维护啊。

**Comment by zhaoshaoquan** [comment]
经过测试，需要手动加一条路由就OK了
sudo route add -net 172.17.0.0/16 192.168.251.2
sudo route add -net 172.18.0.0/16 192.168.251.2

**Comment by wenjunxiao** [comment]
> 经过测试，需要手动加一条路由就OK了 sudo route add -net 172.17.0.0/16 192.168.251.2 sudo route add -net 172.18.0.0/16 192.168.251.2

路由在服务启动的时候会自动添加，无效手动添加，你看看Mac上本地服务的日志是不是权限不够导致的

**Comment by wenjunxiao** [comment]
@zby-universal 看下Mac上的服务的日志

**Comment by ZarrianShi** [comment]
> @zby-universal 看下Mac上的服务的日志

  @zhaoshaoquan 的方法有效，看了下日志确实没有加172.17网段路由的相关内容，日志内容如下：
```
2023/08/30 12:07:27 config file => /usr/local/opt/docker-connector/bin/etc/docker-connector.conf
2023/08/30 12:07:27 interface => utun11
2023/08/30 12:07:27 command => ifconfig utun11 inet 192.168.251.2 192.168.251.1 netmask 255.255.255.255 up
2023/08/30 12:07:27 command => route -n add -host 192.168.251.2 -interface utun11
2023/08/30 12:07:27 drawin setup done.
2023/08/30 12:07:27 listen => 127.0.0.1:2511
2023/08/30 12:08:06 client init => 127.0.0.1:49310
2023/08/30 12:08:06 send controls => 127.0.0.1:49310 map[]
2023/08/30 12:08:06 reply client => 127.0.0.1:49310 0
```

**Comment by weizewei** [comment]
我应该跟你一样，程序使用的config file。不是命令生成的conf文件地址

**Comment by wenjunxiao** [comment]
@xocodergit @zhaoshaoquan @weizewei   安装程序的配置错误导致，已经修复，重新安装即可
