### ISSUE TITLE
How could I connect my container with hostname?

### ISSUE THREAD

**Issue by tuyunlei** [wenjunxiao/mac-docker-connector#2]
I have used `docker run -h xxx` to set my container's hostname. And the containers can connect with each other by hostname. So is it possible to connect the container with the hostname from mac?

**Comment by wenjunxiao** [comment]
Use the hostname to connect to the container from the host machine requires the support of the host machine's DNS, or you can use just save the domain name mapping to `/etc/hosts` by following commands:
`docker ps -qa| xargs docker inspect --format "{{.Config.Hostname}} {{range .NetworkSettings.Networks}}{{.IPAddress}} {{end}}"|awk '{for(i=2;i<=NF;i++)print $i,$1}'`
