### ISSUE TITLE
m1的mac 使用brew start有报错

### ISSUE THREAD

**Issue by zzjbattlefield** [wenjunxiao/mac-docker-connector#20]
按照教程步骤执行命令 在执行
`sudo brew services start docker-connector`
然后输入完密码后提示
`Service `docker-connector` already started, use `brew services restart docker-connector` to restart.`
但是我使用brew services list查看显示 docker-connector并没有启动成功
```
Name             Status User File
docker-connector none   root 
```
不使用sudo 进行start的时候就有报错
`docker-connector error  19968 root ~/Library/LaunchAgents/homebrew.mxcl.docker-connector.plist`
请问我应该如何解决？

**Comment by wenjunxiao** [comment]
> 按照教程步骤执行命令 在执行 `sudo brew services start docker-connector` 然后输入完密码后提示 `Service `docker-connector`already started, use`brew services restart docker-connector` to restart.` 但是我使用brew services list查看显示 docker-connector并没有启动成功
> 
> ```
> Name             Status User File
> docker-connector none   root 
> ```
> 
> 不使用sudo 进行start的时候就有报错 `docker-connector error 19968 root ~/Library/LaunchAgents/homebrew.mxcl.docker-connector.plist` 请问我应该如何解决？

需要sudo才能有权限操作路由，你用restart能启动成功吗？

**Comment by zzjbattlefield** [comment]
> > 按照教程步骤执行命令 在执行 然后输入完密码后提示 docker-connectorbrew services restart docker-connector 但是我使用brew services list查看显示 docker-connector 并没有启动成功`sudo brew services start docker-connector``Service ``already started, use`` to restart.`
> > ```
> > Name             Status User File
> > docker-connector none   root 
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 不使用sudo 进行start的时候就有报错 请问我应该如何解决？`docker-connector error 19968 root ~/Library/LaunchAgents/homebrew.mxcl.docker-connector.plist`
> 
> 需要sudo才能有权限操作路由，你用restart能启动成功吗？

我后来发现是我在执行brew services list时没有加上sudo 加上sudo就显示开启成功了
但是我后来发现还是ping不通我的容器ip 因为`/opt/homebrew/etc/docker-connector.conf`有一份默认生成的配置文件 修改这个路径的配置文件是不生效的
后来查看日志发生它读取的是`/opt/homebrew/opt/docker-connector/bin/etc/docker-connector.conf` 这个路径的配置是不存在的
后来我自己手动生成后就可以ping通了
我brew上安装的docker-connector的版本是`wenjunxiao/brew/docker-connector: stable 3.1`
我的操作系统是`m1pro macos 13.5`
