### ISSUE TITLE
不能ping通

### ISSUE THREAD

**Issue by AlphaIX** [wenjunxiao/mac-docker-connector#4]
我完全照文档操作，还是不能ping通容器

**Comment by wenjunxiao** [comment]
> 我完全照文档操作，还是不能ping通容器
@AlphaIX 
1、什么版本的Mac，是Mac M1吗？
2、另外日志/usr/local/var/log/docker-connector.log的内容？
3、配置文件/usr/local/etc/docker-connector.conf是怎么样的？
4、Docker版本是什么？
5、要访问的容器的网络是什么，可以通过docker inspect 和docker network查看网络的的Driver是什么？

**Comment by AlphaIX** [comment]
感谢你的回复
1.MacBook Pro
2.已经被我删了0.0
3. route 192.168.0..0/24
4. docker for Mac 2.x版本
5. 网络是我自定义的网络使用docker network create   Driver bridge

**Comment by wenjunxiao** [comment]
你要ping的容器IP地址是192.168.0.y吗？除docker外，你本地关联的还有192.168网段的网络吗，通过netstat -nr -f inet检查一下本地的路由信息。另外docker端的服务容器需要保证--net host --cap-add NET_ADMIN这两个选项。
另外我自己目前使用的是Docker Desktop 3.6.0，所有docker里面自定义的网络172.100.0.0/16都可以正常访问
https://blog.csdn.net/wenjun_xiao/article/details/106320242

**Comment by AlphaIX** [comment]
是的 我的容器ip 被我设置成固定ip 192.168.0.x，  docker端的服务容器--net host --cap-add NET_ADMIN这两个选项 我也加了。我本wifi 好像确实是192.168网段，会不会这个有影响，我晚上回去把docker network 重新配置一个 172.xxx的网段试一下

**Comment by AlphaIX** [comment]
最新情况：我把你的所有安装生成的容器(connect等) rm删除，brew卸载docker-connector后。相关镜像也删除。
然后重启了docker。重启了电脑。
奇怪的事情发生了：
我使用`docker network create --subnet 172.100.0.0/16 testnet` 命令创建了一个自定义网络
然后使用 `docker run -it --network testnet --ip 172.100.0.11 centos:7 /bin/bash` 创建了一个容器
ctrl+p+q返回宿主机后，ping 172.100.0.11 居然可以ping通！！！！！！！我都卸载删除相关组件了 居然还能ping通，
我又尝试 docker network create --subnet 182.100.0.0/6 testnet2 创建一个自定义网络，然后使用testnet2网络创建的容器式不能ping通的。
各种折腾一番后，确定只有172.100.0.0/16 这个网段是可以ping通的，不过端口不通。
我的问题是：为啥能ping通。应该ping不通才对

**Comment by wenjunxiao** [comment]
能ping通的原因有很多，你需要检查Mac的路由表；能ping通，但端口不通，有可能并没有路由到指定的容器，也有可能是防火墙等原因导致。这个问题与你本身环境各个参数有关，如果你卸载之前没有清理配置，可能会有遗留的路有信息，但这也仅限于未重启的情况下。所以如果你想弄清楚为什么一个能ping通，另一个不能ping。第一需要仔细核对两个子网的参数（最好通过对比工具，而不是眼睛直接查看）；第二，需要仔细核查本地路有表的情况；第三，也可以在容器中抓包确认ping流量是否达到容器。情况根据环境各异，需要你去仔细分析所有的参数设置，只凭目前提供的信息来说无法给你提供确切的答案
