### ISSUE TITLE
是否可以配置为访问127.0.0.1转发到容器ip上

### ISSUE THREAD

**Issue by gofunbox** [wenjunxiao/mac-docker-connector#6]
由于项目原因需要访问127.0.0.1:80到容器上
现在通过默认的插件配置 访问http://172.17.0.1是可以访问到容器的
不太明白proxy的配置用途，配置如下，好像也没有达到我的目的
proxy 127.0.0.1:80:80

难道只能安装一个ng转发么？ 求教，谢谢

**Comment by wenjunxiao** [comment]
proxy是为了让容器内的服务可以访问你主机中监听127.0.0.1，比如回调接口。127.0.0.1转发到容器没有意义，因为如果是你本机访问，应该直接用容器的地址，如果是提供给其他人用，可以选择用ng，或者让对方安装docker-accessor，同时开启expose。这么做主要是考虑避免主机开启太多对外开放的端口而不可控或公司的安全扫描，同时也因为外网IP会经常变化
