### ISSUE TITLE
mac 系统12.2.1 brew install 提示 Your Command Line Tools are too outdated

### ISSUE THREAD

**Issue by zxavier94** [wenjunxiao/mac-docker-connector#8]
xxxx ~ % brew install wenjunxiao/brew/docker-connector
Updating Homebrew...
==> Tapping wenjunxiao/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wenjunxiao/homebrew-brew'...
remote: Enumerating objects: 64, done.
remote: Counting objects: 100% (64/64), done.
remote: Compressing objects: 100% (41/41), done.
remote: Total 64 (delta 32), reused 44 (delta 16), pack-reused 0
Receiving objects: 100% (64/64), 9.55 KiB | 126.00 KiB/s, done.
Resolving deltas: 100% (32/32), done.
Tapped 2 formulae (16 files, 23.4KB).
Warning: You are using macOS 12.
We do not provide support for this pre-release version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Twitter or any other official channels. You are responsible for resolving
any issues you experience while you are running this
pre-release version.

==> Installing docker-connector from wenjunxiao/brew
==> Downloading https://github.com/wenjunxiao/mac-docker-connector/releases/download/v3.1/docker-connector-darwin.tar.gz
==> Downloading from https://objects.githubusercontent.com/github-production-release-asset-2e65be/266031479/3f51cb4b-e37
######################################################################## 100.0%
Error: Your Command Line Tools are too outdated.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 13.0.

Error: Your Command Line Tools (CLT) does not support macOS 12.
It is either outdated or was modified.
Please update your Command Line Tools (CLT) or delete it if no updates are available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/more/.
You should download the Command Line Tools for Xcode 13.0.

**Comment by wenjunxiao** [comment]
You should upgrade the Command Line Tools.
