### ISSUE TITLE
brew tap wenjunxiao/brew, failed 

### ISSUE THREAD

**Issue by DBAAJ** [wenjunxiao/mac-docker-connector#9]
$ brew tap wenjunxiao/brew
==> Tapping wenjunxiao/brew
Cloning into '/usr/local/Homebrew/Library/Taps/wenjunxiao/homebrew-brew'...
fatal: unable to access 'https://github.com/wenjunxiao/homebrew-brew/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 
Error: Failure while executing; `git clone https://github.com/wenjunxiao/homebrew-brew /usr/local/Homebrew/Library/Taps/wenjunxiao/homebrew-brew --origin=origin --template=` exited with 128.

**Comment by wenjunxiao** [comment]
Reinstall the `git` and try again

**Comment by wenjunxiao** [comment]
> $ brew tap wenjunxiao/brew ==> Tapping wenjunxiao/brew Cloning into '/usr/local/Homebrew/Library/Taps/wenjunxiao/homebrew-brew'... fatal: unable to access 'https://github.com/wenjunxiao/homebrew-brew/': LibreSSL SSL_connect: SSL_ERROR_SYSCALL in connection to github.com:443 Error: Failure while executing; `git clone https://github.com/wenjunxiao/homebrew-brew /usr/local/Homebrew/Library/Taps/wenjunxiao/homebrew-brew --origin=origin --template=` exited with 128.


Reinstall the git and try again
